/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.26
 * Generated at: 2015-12-01 13:18:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.LinkedList;
import java.util.Locale;
import java.util.Currency;
import java.text.NumberFormat;
import Data.EnglishAuction;
import Data.DutchAuction;
import Data.Account;
import java.io.File;
import Data.Bid;
import java.util.ResourceBundle;

public final class auctionlist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("Data.Bid");
    _jspx_imports_classes.add("java.util.ResourceBundle");
    _jspx_imports_classes.add("java.util.Locale");
    _jspx_imports_classes.add("Data.Account");
    _jspx_imports_classes.add("Data.DutchAuction");
    _jspx_imports_classes.add("java.util.Currency");
    _jspx_imports_classes.add("java.util.LinkedList");
    _jspx_imports_classes.add("java.text.NumberFormat");
    _jspx_imports_classes.add("Data.EnglishAuction");
    _jspx_imports_classes.add("java.io.File");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	//Check client session
	session = request.getSession();
	session.setAttribute("adminView", false);
	if (session == null || session.getAttribute("account") == null){
		session.setAttribute("redirectLink", "index.jsp");
		session.setAttribute("redirectMsg", "You are currently not signed in, please sign in before viewing this page. Redirecting you home shortly.");
		response.sendRedirect("redirect.jsp");		
	}
	
	LinkedList<EnglishAuction> englishAuctions = (LinkedList<EnglishAuction>)session.getAttribute("englishAuctionList");
	LinkedList<DutchAuction> dutchAuctions = (LinkedList<DutchAuction>)session.getAttribute("dutchAuctionList");
	int count = 0;
	String lang;
	if(session==null || session.getAttribute("language") == null )
		lang = "Language.lang_en_ca";
	else
		lang = session.getAttribute("language").toString();
	ResourceBundle resource = ResourceBundle.getBundle(lang);
	Locale curLocale;
	if(lang == "Language.lang_en_ca") curLocale = Locale.CANADA;
	else curLocale = Locale.CANADA_FRENCH;
	NumberFormat format = NumberFormat.getCurrencyInstance(curLocale);

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("    <title>");
      out.print(resource.getString("auctionSite"));
      out.write("</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap Core CSS -->\r\n");
      out.write("    <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom CSS -->\r\n");
      out.write("    <link href=\"css/heroic-features.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Navigation -->\r\n");
      out.write("    <nav class=\"navbar navbar-inverse navbar-fixed-top\" role=\"navigation\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <!-- Brand and toggle get grouped for better mobile display -->\r\n");
      out.write("            <div class=\"navbar-header\">\r\n");
      out.write("                <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\">\r\n");
      out.write("                    <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                </button>\r\n");
      out.write("                <a class=\"navbar-brand\" href=\"#\">");
      out.print(resource.getString("auctionSite"));
      out.write("</a>\r\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Collect the nav links, forms, and other content for toggling -->\r\n");
      out.write("            <!-- /.navbar-collapse -->\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <!-- /.container -->\r\n");
      out.write("    </nav>\r\n");
      out.write("    <div id=\"userWelcome\">\r\n");
      out.write("    \t<h2>");
      out.print(resource.getString("hello") );
      out.write(", <small>");
      out.print( ((Account)session.getAttribute("account")).getUsername());
      out.write("</small></h2><br/>\r\n");
      out.write("    \t");

			if(((Account)session.getAttribute("account")).isAdmin()){
				out.println("<a class=\"btn btn-primary\" href=\"/ArtAuction/AdminViewAuctionListServlet\" role=\"Button\">"+resource.getString("adminControls")+"</a>");

    		}
    	
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Page Content -->\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("        <!-- Jumbotron Header -->\r\n");
      out.write("        <header class=\"jumbotron hero-spacer\">\r\n");
      out.write("            <h1>");
      out.print(resource.getString("auctionMessage"));
      out.write("</h1>\r\n");
      out.write("\t\t\t<img alt=\"auction\" src=\"auction.png\" style=\"display: block; margin-left:auto; margin-right:auto;\" />\r\n");
      out.write("        </header>\r\n");
      out.write("\r\n");
      out.write("        <hr>\r\n");
      out.write("         <div class=\"row\">\r\n");
      out.write("            <div class=\"col-lg-12\">\r\n");
      out.write("                <h3>");
      out.print(resource.getString("listedAuctions"));
      out.write("</h3>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- /.row -->\r\n");
      out.write("\r\n");
      out.write("        <!-- Page Features -->\r\n");
      out.write("        <!-- Nav tabs -->\r\n");
      out.write("        <div>\r\n");
      out.write("\t  \t\t<ul class=\"nav nav-tabs\" role=\"tablist\">\r\n");
      out.write("\t    \t\t<li role=\"presentation\" class=\"active\"><a href=\"#english\" aria-controls=\"englsih\" role=\"tab\" data-toggle=\"tab\">");
      out.print(resource.getString("englishAuction"));
      out.write("</a></li>\r\n");
      out.write("\t    \t\t<li role=\"presentation\"><a href=\"#dutch\" aria-controls=\"dutch\" role=\"tab\" data-toggle=\"tab\">");
      out.print(resource.getString("dutchAuction"));
      out.write("</a></li>\r\n");
      out.write("\t  \t\t</ul>\r\n");
      out.write("\t  \t\t<!-- Tab panes -->\r\n");
      out.write("\t  \t\t<div class=\"tab-content\">\r\n");
      out.write("\t    \t\t<div role=\"tabpanel\" class=\"tab-pane active\" id=\"english\">\r\n");
      out.write("\t    \t\t\t<div class=\"row text-center\">\r\n");
      out.write("        \t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "AuctionInit.jsp", out, false);
      out.write("\r\n");
      out.write("        \t");

        		if (englishAuctions != null) {
        	        		for(EnglishAuction auction : englishAuctions) {
        	        			out.println("<div class=\"col-md-3 col-sm-6 hero-feature\"><div class=\"thumbnail\"> <img src=\"/ArtAuction/Image?id=" + auction.getImageid() + "\" style=\"width:250px;height:250px;\"><div class=\"caption\"><h3>" + auction.getTitle() + "</h3><p>" + auction.getDescription() + "<br>"+ resource.getString("startingPrice") + format.format(auction.getStartingPrice()) +"</p><p><a href=\"/ArtAuction/EnglishAuctionServlet?auctid=" + auction.getId()+ "\" class=\"btn btn-primary\">View Auction</a></p> </div> </div></div>");
        	        		}
        	        	}
        	
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\t   \t</div>\r\n");
      out.write("\t    \t\t<div role=\"tabpanel\" class=\"tab-pane fade\" id=\"dutch\">\r\n");
      out.write("\t    \t\t\t<div class=\"row text-center\">\r\n");
      out.write("        \t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "AuctionInitDutch.jsp", out, false);
      out.write("\r\n");
      out.write("        \t\t\t");
 
        				if (dutchAuctions != null) {
        					for(DutchAuction auction : dutchAuctions) {
        						out.println("<div class=\"col-md-3 col-sm-6 hero-feature\"><div class=\"thumbnail\" style=\"height:550px;\"> <img src=\"/ArtAuction/Image?id=" + auction.getImageid() + "\" style=\"width:250px;height:250px;\"><div class=\"caption\"><h3>" + auction.getTitle() + "</h3><p>" + auction.getDescription() + "<br>" + resource.getString("startingPrice") + format.format(auction.getInitialCost()) + "</p><p><a href=\"/ArtAuction/DutchAuctionServlet?auctid=" + auction.getId()+ "\" class=\"btn btn-primary\">"+resource.getString("viewAuction")+"</a></p> </div> </div></div>");
        					}
        				}
        			
      out.write("\r\n");
      out.write("        \t\t</div>\r\n");
      out.write("\t    \t</div>\r\n");
      out.write("\t  \t</div>\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("          \r\n");
      out.write("        <hr>\r\n");
      out.write("\r\n");
      out.write("        <!-- Footer -->\r\n");
      out.write("        <footer>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-12\">\r\n");
      out.write("                    <p>");
      out.print(resource.getString("copywrite"));
      out.write(" &copy; Red Leaf Technologies 2015</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </footer>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("\t    <!-- jQuery -->\r\n");
      out.write("    <script src=\"js/jquery.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap Core JavaScript -->\r\n");
      out.write("    <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
